
title: "MP2 - Final"
author: "Zoe Meers, Natasha Jadavji, Christine Yee"
date: "3/20/2017"
output: html_document

```{r, message=FALSE, echo=FALSE}
#load data sets
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
library(maps)
library(maptools)
library(mapdata)
library(dplyr)
```
These maps from the FEC data show the total contributions that would help a candidate in the 2012 election be elected grouped by party identification and state residency. 

```{r, message=FALSE}
#filter candidates by year
candidates2012<-filter(candidates, cand_election_yr=="2012")
#filter contributions by individual contributions to HELP a candidate be elected
contributions2012<-filter(contributions, transaction_type=="24E")
#filter negative contributions
contributions2012<-filter(contributions2012, transaction_amt==gsub('-[A-z ]*', '', transaction_amt))
contributions2012<-filter(contributions2012, transaction_amt==gsub('0', '', transaction_amt))

```
```{r, message=FALSE}
#filter transactions for 2012 election only.
#2010 midterms were helf on the 11/02/10, so transactions on or after this date are most likely for 2012
contributions2012<- filter(contributions, transaction_dt>="11022010")
#filters for transaction dates before the 2012 election. We don't want contributions for the 2014 midterms.
contributions2012<- filter(contributions, transaction_dt<"11052012")
```

```{r, message=FALSE}
#Finds contributions from 2012 election and sums transaction amount by candidate ID
sum_cand<-contributions2012 %>%
  group_by(cand_id) %>%
  summarise(transaction_amt=sum(transaction_amt))

```


```{r, message=FALSE}
#Joins candidate DF with transaction DF by candidate ID
party_id <- candidates2012 %>%
  inner_join(sum_cand, by = ("cand_id"))
```


```{r, message=FALSE}
#Splits contributions and candidates by party identification
#democrats2012 - candidates
democrats2012<- filter(party_id, cand_party_affiliation=="DEM")
#repubs2012 - candidates
republicans2012 <- filter(party_id, cand_party_affiliation=="REP")
```


```{r, message=FALSE}
# sum of transaction amt by state - democrats
sum_dem <- democrats2012 %>% 
  group_by(cand_office_state) %>% 
  summarise(transaction_amt = sum(transaction_amt)) 
#sum of transaction amt by state - republicans
sum_rep <- republicans2012 %>% 
  group_by(cand_office_state) %>% 
  summarise(transaction_amt = sum(transaction_amt))
```
```{r, message=FALSE}
#rename cand_office_state variable to state
sum_dem <- rename(sum_dem, "State"=cand_office_state)
sum_rep <- rename(sum_rep, "State"=cand_office_state)
```
```{r, message=FALSE}
#cut US, PR, AS, GU, DC, MP, VI from States
sum_dem <- sum_dem[-c(3,8,12,41,47,50), ]
sum_rep <- sum_rep[-c(11,45), ]
```

```{r, message=FALSE, echo=FALSE}
#Change state abbreviations to name for sum_dem in order to match states with map data later on.
sum_dem$State <- gsub("AL", "alabama", sum_dem$State)
sum_dem$State <- gsub("AK", "alaska", sum_dem$State)
sum_dem$State <- gsub("AR", "arkansas", sum_dem$State)
sum_dem$State <- gsub("AZ", "arizona", sum_dem$State)
sum_dem$State <- gsub("CA", "california", sum_dem$State)
sum_dem$State <- gsub("CO", "colorado", sum_dem$State)
sum_dem$State <- gsub("CT", "connecticut", sum_dem$State)
sum_dem$State <- gsub("DE", "delaware", sum_dem$State)
sum_dem$State <- gsub("FL", "florida", sum_dem$State)
sum_dem$State <- gsub("GA", "georgia", sum_dem$State)
sum_dem$State <- gsub("HI", "hawaii", sum_dem$State)
sum_dem$State <- gsub("IA", "iowa", sum_dem$State)
sum_dem$State <- gsub("ID", "idaho", sum_dem$State)
sum_dem$State <- gsub("IL", "illinois", sum_dem$State)
sum_dem$State <- gsub("IN", "indiana", sum_dem$State)
sum_dem$State <- gsub("KS", "kansas", sum_dem$State)
sum_dem$State <- gsub("KY", "kentucky", sum_dem$State)
sum_dem$State <- gsub("LA", "louisiana", sum_dem$State)
sum_dem$State <- gsub("MA", "massachusetts", sum_dem$State)
sum_dem$State <- gsub("MD", "maryland", sum_dem$State)
sum_dem$State <- gsub("ME", "maine", sum_dem$State)
sum_dem$State <- gsub("MI", "michigan", sum_dem$State)
sum_dem$State <- gsub("MN", "minnesota", sum_dem$State)
sum_dem$State <- gsub("MO", "missouri", sum_dem$State)
sum_dem$State <- gsub("MS", "mississippi", sum_dem$State)
sum_dem$State <- gsub("MT", "montana", sum_dem$State)
sum_dem$State <- gsub("NC", "north carolina", sum_dem$State)
sum_dem$State <- gsub("ND", "north dakota", sum_dem$State)
sum_dem$State <- gsub("NE", "nebraska", sum_dem$State)
sum_dem$State <- gsub("NH", "new hampshire", sum_dem$State)
sum_dem$State <- gsub("NJ", "new jersey", sum_dem$State)
sum_dem$State <- gsub("NM", "new mexico", sum_dem$State)
sum_dem$State <- gsub("NV", "nevada", sum_dem$State)
sum_dem$State <- gsub("NY", "new york", sum_dem$State)
sum_dem$State <- gsub("OH", "ohio", sum_dem$State)
sum_dem$State <- gsub("OK", "oklahoma", sum_dem$State)
sum_dem$State <- gsub("OR", "oregon", sum_dem$State)
sum_dem$State <- gsub("PA", "pennsylvania", sum_dem$State)
sum_dem$State <- gsub("RI", "rhode island", sum_dem$State)
sum_dem$State <- gsub("SC", "south carolina", sum_dem$State)
sum_dem$State <- gsub("SD", "south dakota", sum_dem$State)
sum_dem$State <- gsub("TN", "tennessee", sum_dem$State)
sum_dem$State <- gsub("TX", "texas", sum_dem$State)
sum_dem$State <- gsub("UT", "utah", sum_dem$State)
sum_dem$State <- gsub("VA", "virginia", sum_dem$State)
sum_dem$State <- gsub("VT", "vermont", sum_dem$State)
sum_dem$State <- gsub("WA", "washington", sum_dem$State)
sum_dem$State <- gsub("WV", "west virginia", sum_dem$State)
sum_dem$State <- gsub("WI", "wisconsin", sum_dem$State)
sum_dem$State <- gsub("WY", "wyoming", sum_dem$State)



```

```{r, message=FALSE, echo=FALSE}
#change state abbreviations to names for sum_rep
sum_rep$State <- gsub("AL", "alabama", sum_rep$State)
sum_rep$State <- gsub("AK", "alaska", sum_rep$State)
sum_rep$State <- gsub("AR", "arkansas", sum_rep$State)
sum_rep$State <- gsub("AZ", "arizona", sum_rep$State)
sum_rep$State <- gsub("CA", "california", sum_rep$State)
sum_rep$State <- gsub("CO", "colorado", sum_rep$State)
sum_rep$State <- gsub("CT", "connecticut", sum_rep$State)
sum_rep$State <- gsub("DE", "delaware", sum_rep$State)
sum_rep$State <- gsub("FL", "florida", sum_rep$State)
sum_rep$State <- gsub("GA", "georgia", sum_rep$State)
sum_rep$State <- gsub("HI", "hawaii", sum_rep$State)
sum_rep$State <- gsub("IA", "iowa", sum_rep$State)
sum_rep$State <- gsub("ID", "idaho", sum_rep$State)
sum_rep$State <- gsub("IL", "illinois", sum_rep$State)
sum_rep$State <- gsub("IN", "indiana", sum_rep$State)
sum_rep$State <- gsub("KS", "kansas", sum_rep$State)
sum_rep$State <- gsub("KY", "kentucky", sum_rep$State)
sum_rep$State <- gsub("LA", "louisiana", sum_rep$State)
sum_rep$State <- gsub("MA", "massachusetts", sum_rep$State)
sum_rep$State <- gsub("MD", "maryland", sum_rep$State)
sum_rep$State <- gsub("ME", "maine", sum_rep$State)
sum_rep$State <- gsub("MI", "michigan", sum_rep$State)
sum_rep$State <- gsub("MN", "minnesota", sum_rep$State)
sum_rep$State <- gsub("MO", "missouri", sum_rep$State)
sum_rep$State <- gsub("MS", "mississippi", sum_rep$State)
sum_rep$State <- gsub("MT", "montana", sum_rep$State)
sum_rep$State <- gsub("NC", "north carolina", sum_rep$State)
sum_rep$State <- gsub("ND", "north dakota", sum_rep$State)
sum_rep$State <- gsub("NE", "nebraska", sum_rep$State)
sum_rep$State <- gsub("NH", "new hampshire", sum_rep$State)
sum_rep$State <- gsub("NJ", "new jersey", sum_rep$State)
sum_rep$State <- gsub("NM", "new mexico", sum_rep$State)
sum_rep$State <- gsub("NV", "nevada", sum_rep$State)
sum_rep$State <- gsub("NY", "new york", sum_rep$State)
sum_rep$State <- gsub("OH", "ohio", sum_rep$State)
sum_rep$State <- gsub("OK", "oklahoma", sum_rep$State)
sum_rep$State <- gsub("OR", "oregon", sum_rep$State)
sum_rep$State <- gsub("PA", "pennsylvania", sum_rep$State)
sum_rep$State <- gsub("RI", "rhode island", sum_rep$State)
sum_rep$State <- gsub("SC", "south carolina", sum_rep$State)
sum_rep$State <- gsub("SD", "south dakota", sum_rep$State)
sum_rep$State <- gsub("TN", "tennessee", sum_rep$State)
sum_rep$State <- gsub("TX", "texas", sum_rep$State)
sum_rep$State <- gsub("UT", "utah", sum_rep$State)
sum_rep$State <- gsub("VA", "virginia", sum_rep$State)
sum_rep$State <- gsub("VT", "vermont", sum_rep$State)
sum_rep$State <- gsub("WA", "washington", sum_rep$State)
sum_rep$State <- gsub("WV", "west virginia", sum_rep$State)
sum_rep$State <- gsub("WI", "wisconsin", sum_rep$State)
sum_rep$State <- gsub("WY", "wyoming", sum_rep$State)

```

```{r, message=FALSE}
#Loading map data 
all_states <- map_data("state")
all_states <- rename(all_states, "State"=region)

#join states together using left join
MyMap_dem <- left_join(all_states, sum_dem, by ="State")
MyMap_rep <- left_join(all_states, sum_rep, by="State")
```


```{r}
#MAPS
options(scipen=999) #variables should not be written in scientific notation
#basic map of the United States, black borders, grey fill
states_map <- ggplot(data = all_states, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")
#Get rid of ggplot background.
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )
#Republican map
Rep_Map <- states_map + 
      geom_polygon(data = MyMap_rep, aes(fill = transaction_amt)) +
     geom_polygon(color = "white", fill = NA) +
    theme_bw() +
      ditch_the_axes + 
  scale_fill_gradient(low="pink", high="red2") + 
  ggtitle("Republican Contributions in the Continguous US - 2012 Election") + theme(plot.title = element_text(size = rel(1))) + theme(legend.title = element_text(face = "bold")) + theme(title = element_text(face = "bold")) + guides(fill=guide_legend(title="Contributions ($)")) + theme(plot.title = element_text(size = rel(1.2)))
Rep_Map

#Democrats map 
Dem_Map <- states_map + 
      geom_polygon(data = MyMap_dem, aes(fill = transaction_amt), color = "white") +
      geom_polygon(color = "white", fill = NA) + theme_bw() + scale_fill_continuous(low="lightblue", high="blue2") +
      ditch_the_axes + ggtitle("Democrat Contributions in the Continguous US - 2012 Election") + theme(plot.title = element_text(size = rel(1.2))) + theme(legend.title = element_text(face = "bold")) + theme(title = element_text(face = "bold")) + guides(fill=guide_legend(title="Contributions ($)"))

Dem_Map

```
